import type { Metadata } from "next";
import { redirect } from "next/navigation";
import { APP_URL, APP_NAME, APP_DESCRIPTION } from "~/lib/constants";
import { getMiniAppEmbedMetadata } from "~/lib/utils";
export const revalidate = 300;

// This is an example of how to generate a dynamically generated share page based on fid:
// Sharing this route e.g. exmaple.com/share/123 will generate a share page for fid 123,
// with the image dynamically generated by the og API route.
export async function generateMetadata({
  params,
  searchParams,
}: {
  params: Promise<{ fid: string }>;
  searchParams: Promise<{ score?: string; stage?: string; badges?: string }>;
}): Promise<Metadata> {
  const { fid } = await params;
  const sp = await searchParams;

  const ogParams = new URLSearchParams({ username: `fid:${fid}` });
  if (sp.score) ogParams.set("score", sp.score);
  if (sp.stage) ogParams.set("stage", sp.stage);
  if (sp.badges) ogParams.set("badges", sp.badges);

  const imageUrl = `${APP_URL}/api/og?${ogParams.toString()}`;

  return {
    title: `${APP_NAME} - Share`,
    openGraph: {
      title: APP_NAME,
      description: APP_DESCRIPTION,
      images: [imageUrl],
    },
    other: {
      "fc:frame": JSON.stringify(getMiniAppEmbedMetadata(imageUrl)),
    },
  };
}

export default function SharePage() {
  // redirect to home page
  redirect("/");
}
